// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6mOLhgnoGoExp93qYhkObhUgRROqDThQ',
    appId: '1:976980168725:web:4522877df78e08d1ef7e1c',
    messagingSenderId: '976980168725',
    projectId: 'delizia-36de6',
    authDomain: 'delizia-36de6.firebaseapp.com',
    storageBucket: 'delizia-36de6.firebasestorage.app',
    measurementId: 'G-4759RKFEQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZdo8FNPkZafu87aE8VxNd1xM5sn3HwZU',
    appId: '1:976980168725:android:cfa56fb54055f57aef7e1c',
    messagingSenderId: '976980168725',
    projectId: 'delizia-36de6',
    storageBucket: 'delizia-36de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ2PuCUIPhDh1ZPMunmmEi898q-lgA1jA',
    appId: '1:976980168725:ios:ac7778aad5290a81ef7e1c',
    messagingSenderId: '976980168725',
    projectId: 'delizia-36de6',
    storageBucket: 'delizia-36de6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ2PuCUIPhDh1ZPMunmmEi898q-lgA1jA',
    appId: '1:976980168725:ios:ac7778aad5290a81ef7e1c',
    messagingSenderId: '976980168725',
    projectId: 'delizia-36de6',
    storageBucket: 'delizia-36de6.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6mOLhgnoGoExp93qYhkObhUgRROqDThQ',
    appId: '1:976980168725:web:09cdf17ca6173a21ef7e1c',
    messagingSenderId: '976980168725',
    projectId: 'delizia-36de6',
    authDomain: 'delizia-36de6.firebaseapp.com',
    storageBucket: 'delizia-36de6.firebasestorage.app',
    measurementId: 'G-SXQG863VM0',
  );
}
